# Generated by Django 5.2 on 2025-04-22 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchallenge',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Correto'), ('I', 'Incorreto')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
