# Generated by Django 5.2 on 2025-04-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_userchallenge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Saída esperada para desafios de código', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Solução esperada para desafios de código', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Código inicial para desafios de programação', null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='code_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='obtained_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('DESCRIPTION', 'Resposta Descritiva'), ('CODE', 'Código'), ('SINGLE_CHOICE', 'Escolha Única'), ('MULTIPLE_CHOICE', 'Múltipla Escolha')], default='CODE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('CORRECT', 'Correto'), ('INCORRECT', 'Incorreto'), ('PARTIAL', 'Parcialmente Correto')], default='PENDING', max_length=10),
        ),
    ]
