# Generated by Django 5.2 on 2025-04-24 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0003_challenge_expected_output_challenge_solution_code_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={
                "ordering": ["order"],
                "verbose_name": "Desafio",
                "verbose_name_plural": "Desafios",
            },
        ),
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["order"],
                "verbose_name": "Opção",
                "verbose_name_plural": "Opções",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "Questão",
                "verbose_name_plural": "Questões",
            },
        ),
        migrations.AlterModelOptions(
            name="track",
            options={
                "ordering": ["order"],
                "verbose_name": "Trilha",
                "verbose_name_plural": "Trilhas",
            },
        ),
        migrations.AlterModelOptions(
            name="userchallenge",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Submissão de Desafio",
                "verbose_name_plural": "Submissões de Desafios",
            },
        ),
        migrations.AlterModelOptions(
            name="usertrackprogress",
            options={
                "verbose_name": "Progresso na Trilha",
                "verbose_name_plural": "Progressos nas Trilhas",
            },
        ),
        migrations.AlterField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("DESCRIPTION", "Description"),
                    ("CODE", "Code"),
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                ],
                default="CODE",
                max_length=20,
                verbose_name="Tipo de Desafio",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="difficulty",
            field=models.CharField(
                choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                default="EASY",
                max_length=10,
                verbose_name="Dificuldade",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Término"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="expected_output",
            field=models.TextField(
                blank=True,
                help_text="Saída esperada para desafios de código",
                null=True,
                verbose_name="Saída Esperada",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="language",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Linguagem de Programação",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="points",
            field=models.IntegerField(verbose_name="Pontos"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="solution_code",
            field=models.TextField(
                blank=True,
                help_text="Solução esperada para desafios de código",
                null=True,
                verbose_name="Código Solução",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Data de Início",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="starter_code",
            field=models.TextField(
                blank=True,
                help_text="Código inicial para desafios de programação",
                null=True,
                verbose_name="Código Inicial",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="challenges.track",
                verbose_name="Trilha",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Está Correta?"),
        ),
        migrations.AlterField(
            model_name="option",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="challenges.question",
                verbose_name="Questão",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.TextField(verbose_name="Texto da Opção"),
        ),
        migrations.AlterField(
            model_name="question",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="challenges.challenge",
                verbose_name="Desafio",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="Texto da Questão"),
        ),
        migrations.AlterField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="track",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="track",
            name="icon",
            field=models.CharField(blank=True, max_length=50, verbose_name="Ícone"),
        ),
        migrations.AlterField(
            model_name="track",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AlterField(
            model_name="track",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordem"),
        ),
        migrations.AlterField(
            model_name="track",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="answer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Resposta Descritiva"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_submissions",
                to="challenges.challenge",
                verbose_name="Desafio",
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="code",
            field=models.TextField(
                blank=True, null=True, verbose_name="Código Submetido"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="code_output",
            field=models.TextField(
                blank=True, null=True, verbose_name="Saída do Código"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="evaluated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Avaliado em"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="feedback",
            field=models.TextField(blank=True, null=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Está Correto?"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="obtained_points",
            field=models.IntegerField(default=0, verbose_name="Pontos Obtidos"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="points_awarded",
            field=models.BooleanField(default=False, verbose_name="Pontos Atribuídos?"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="selected_options",
            field=models.ManyToManyField(
                blank=True, to="challenges.option", verbose_name="Opções Selecionadas"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("CORRECT", "Correto"),
                    ("INCORRECT", "Incorreto"),
                    ("PARTIAL", "Parcialmente Correto"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="submission_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Submissão"
            ),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Submetido em"),
        ),
        migrations.AlterField(
            model_name="userchallenge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="usertrackprogress",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completado em"
            ),
        ),
        migrations.AlterField(
            model_name="usertrackprogress",
            name="completed_challenges",
            field=models.ManyToManyField(
                blank=True,
                to="challenges.challenge",
                verbose_name="Desafios Completados",
            ),
        ),
        migrations.AlterField(
            model_name="usertrackprogress",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="Completo?"),
        ),
        migrations.AlterField(
            model_name="usertrackprogress",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="challenges.track",
                verbose_name="Trilha",
            ),
        ),
        migrations.AlterField(
            model_name="usertrackprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
    ]
