# Generated by Django 5.2 on 2025-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_aluno",
            field=models.BooleanField(default=False, verbose_name="é aluno?"),
        ),
    ]
