# Generated by Django 5.2 on 2025-05-16 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_is_aluno"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="pontuação",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="foto de perfil",
            ),
        ),
    ]
