# Generated by Django 5.2 on 2025-04-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_username_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_aluno",
            field=models.BooleanField(default=False, verbose_name="É aluno?"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
