# Generated by Django 5.2 on 2025-04-23 17:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_is_aluno_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AlunoUser",
            fields=[],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
