# Generated by Django 5.2 on 2025-04-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_is_aluno_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="temp_username",
                help_text="Obrigatório. 150 caracteres ou menos. Letras, dígitos e @/./+/-/_ apenas.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
