# Generated by Django 5.2 on 2025-04-24 19:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_adminuser_alunouser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminUser",
        ),
        migrations.DeleteModel(
            name="AlunoUser",
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[],
            options={
                "verbose_name": "Administrador",
                "verbose_name_plural": "Administradores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
